name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      id: aws-creds-cache
    
    - name: Login to Amazon ECR
      if: steps.cache.outputs.cache-hit != 'true'  # Skip if credentials were cached
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/lambda_scraping:latest .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/lambda_scraping:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Restore AWS Credentials from Cache
      uses: actions/cache@v2
      with:
        path: /tmp/.aws
        key: ${{ runner.os }}-aws-creds-${{ hashFiles('**/terraform.tf') }}
      if: success()  # Only restore cache if previous step succeeded

    - name: Configure AWS Credentials
      if: success()  # Only configure credentials if cache was restored
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ steps.aws-creds-cache.outputs.access_key_id }}
        aws-secret-access-key: ${{ steps.aws-creds-cache.outputs.secret_access_key }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infra

    - name: Check Deployment Status
      run: terraform output deployment_status
      id: deployment_status

    - name: Rollback on Failure
      if: ${{ steps.deployment_status.outputs.status != 'success' }}
      run: terraform destroy -auto-approve
      # env:
      #   TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   TF_VAR_aws_region: us-east-1